---
title: "Datacamp_kmeans_clustering"
author: "Tinus Cloete"
date: "14 June 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# DataCamp tutorial

[](https://www.datacamp.com/community/tutorials/k-means-clustering-r)

My goal vir vanogged: Identify the package that can be used to do k-means clustering in R

## Load Data

Read the raw data... (note ek cache dit om te probeer tyd spaar....)

```{r, cache = T}

# Load the csv files

apr14 <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/uber-tlc-foil-response/master/uber-trip-data/uber-raw-data-apr14.csv")
may14 <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/uber-tlc-foil-response/master/uber-trip-data/uber-raw-data-may14.csv")
jun14 <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/uber-tlc-foil-response/master/uber-trip-data/uber-raw-data-jun14.csv")
jul14 <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/uber-tlc-foil-response/master/uber-trip-data/uber-raw-data-jul14.csv")
aug14 <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/uber-tlc-foil-response/master/uber-trip-data/uber-raw-data-aug14.csv")
sep14 <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/uber-tlc-foil-response/master/uber-trip-data/uber-raw-data-sep14.csv")

```

Combing the data

```{r}

library(dplyr)

data14 <- bind_rows(apr14, may14, jun14, jul14, aug14, sep14)

summary(data14)

```

## Data Preparation

## K-Means Clustering

```{r}

# kmeans

```

